### ISSUE TITLE
Bank Eat/Weild/Ect. wont bind to shift key

### ISSUE THREAD

**Issue by ayyyylma0** [geheur/More-menu-entry-swaps#17]
It will bind to other keys. It has previously worked with shift key.

**Comment by geheur** [comment]
This was fixed a while ago.

**Comment by TheAgorian** [comment]
Good evening, 

I'm pinging this topic because the issue remains. I recently learned about the profile importing from RuneLite and I am trying to utilize menu entry swapper. The options will not work when trying to use Shift as the hotkey. 

Any assistance is greatly appreciated :)
